spring:
  application:
    name: cheongyagtalk-api

  datasource:
    url: jdbc:postgresql://localhost:5432/talk_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발: update/ create-drop, 운영: none/validate 권장
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace  # 바인드 파라미터까지 보고 싶을 때(버전별 패키지 다를 수 있음)

# 포트 8081로 연결
server:
  port: 8081

# 5fcd3663cd9fceab25ea2365cf594fa0b30b1510